# Variables

Variables are symbolic names associated with information, values, which are paired with storage locations on the computer. In other words, if you wish to be able to access a piece of information, you store that information in memory and access it using this symbolic name, the variable, that has been linked to that location.

We assign values to variables using the `=` opperator.

In [3]:
i = 5
a = "Hello World!"

Notes on variable names:
* They can **only** contain letters, digits, or underscores `_`
* They **cannot** start with digits
* Variable names that start with underscores like `__special` have a special meaning and should be avoided until you understand the convention.

You can display these values using the built-in python function, `print`, that prints things as text. To do this:
* Call the function (i.e., tell Python to run it) by using its name
* Provide values to the function (i.e., the things to print) in parentheses
* The values passed to the function are called **arguments**

In [4]:
print(a)

Hello World!


To add text to your print statment, use a string formatting method. For example:

In [8]:
print("i = {}".format(i))
print("{} i = {}".format(a,i))
print("{1} i = {0}".format(i,a))

i = 5
Hello World! i = 5
Hello World! i = 5


You have probably noticed that we were able to use the variables `i` and `a` across cells. This is because during a single interactive session, or in this case a jupyter notebook, variables persist - or maintain their memory location pairing and the most recently assigned value - beyond the cell (individual code block) they are defined within. Another way to say this is that variables defined as the above examples are global in scope.

### What is scope?
Scope describes the region of your code where a variable is defined. A global variable is one accessible anywhere in the code. There are also local variables, those only defined within a code-block. For example, variables defined within functions can only be accessed in that function.

**NOTE:** In many languages, loops and conditionals (for, while; if, else) also act as scope blocks. This is not the case in Python. In Python, scope is set by functions, classes, and modules: key words that we will return to later.

In [9]:
print(b)

NameError: name 'b' is not defined

**Why did this fail?**

The variable b was not previously defined, it must be defined - created - before we can use it.

In [11]:
def my_function():
    b = 5
    print(b)

my_function()

5


In [12]:
print(b)

NameError: name 'b' is not defined

**Why did this fail?**

This time, `b` was defined, which is why printing `b` in the function did work. However, `b` is defined within the local scope of the function `my_function`, but outside the function there is no variable `b` defined.

# Data types

Values in a program will have a specific **type** which determines the types of operations (methods) that can be performed on that value.

There is a built-in method: `type` which can be used to determine the type of a variable.

In [19]:
print(type(5))

<class 'int'>


In [21]:
a = 5
print(type(a))

<class 'int'>


In [20]:
a = "Hello World!"
print(type(a))

<class 'str'>


In [22]:
a = 5.5
print(type(a))

<class 'float'>


## Common data types
The three examples above cover the three main basic types we will encounter: `int`, `float`, and `string`

### int
An `int` is a signed (positive or negative) whole number. Standard ints are 4 bytes, so can range from -2147483648 to 2147483647. 

**Where does this range come from?**
Let's consider the example of a small int: a small int is 1 byte, meaning it can range from -128 to 127. One byte is 8 bits (a bit holding a binary value 0 or 1), so there are 7 bits for the integer value - allowing the max value 2^7 - and one bit for the sign.

### float
A `float` is a floating point (real) number, which can have fractional or decimal values. Mathematically, there are an infinite number of real numbers. In computing, the `float` type has to have a finite size, usually 4 bytes, so by definition there will be a finite set of numbers that can be expressed this way. Generally the range and precision of floats is set using this exact representation form:

`significand x base^exponent`

where the significand is an integer, the length of which sets the precision of the number, and the exponent is also an integer. In computing the base is 2 (binary). The standard 32-bit - single precision - format is 24 bits of precision, 7 bits for the exponent, and one for the sign.

### string
A character string, usually called a `string` or `str` is simply text. The more fundamental data type is the `char` - a 1-byte type representing a single letter, number, or symbol. In python, there is no single character type, a single character is simply a string of length one. A string is a character array, meaning unlike ints and floats it is not a single value. Therefore, although strings are often manipulated as if they were single values, there a few fundamental differences that we will encounter resulting from the non-singular nature of the `string` type. 

## Assigning type in python

You may have noticed that when checking type in the examples above, I used the variable `a` in each case. Why did this work? We know that `a` is a global variable and we saw that after I assigned `a` the value `5` it was an `int`. 


What type is `a` now?

In [18]:
print(type(a))

<class 'float'>


Why is `a` a float currently?

Because the last code cell had the line `a = 5.5`.

So, we see that when we assign a value to a variable in Python that sets the type for that variable, but that type is not fixed. We can change the type for a variable by assigning it a value of a different type. This is not the case for some languages where you - in those cases you generally assign the type as part of the variable declaration, e.g. `int a = 5`.

## Operations

A value's type determines what operations can be performed on that value. Some of the most basic operations are things like adding (`+`), subtracting (`-`), and multiplying (`*`).

When talking about numbers, all of these operations seem pretty straight forward, and indeed all are possible for `int` and `float` types.

In [40]:
a = 5+3
print(a)

a = 5-3
print(a)

a = 5*3
print(a)

8
2
15


In [41]:
a = 5.5+3.5
print(a)

a = 5.5-3.5
print(a)

a = 5.5*3.5
print(a)

9.0
2.0
19.25


Strings are a bit different.

Addition still makes sense, it is simply the concatenation of the strings.

In [42]:
a = 'Hello' + ' ' + 'World!'
print(a)

Hello World!


Multiplication can be thought of as repeated addition. So multiplying a string by an integer *N* will simply create a new string consisting of the original string repeated *N* times.

In [43]:
a = '-' * 10
print(a)

----------


Subtraction is less obvious. A string is an array of characters, subtracting one string from another is not a simple process that would always work the same way. For example, how would we interpret `'Hello World!' - 'l'`? There are three `l` characters in the first string, which should we remove? Let's try anyway:

In [44]:
a = 'Hello World!' - 'l'

TypeError: unsupported operand type(s) for -: 'str' and 'str'

### Mixing types and type conversion

What about performing operations that mix types?

What would it mean to add a number and a string? For example, how should we interpret `1 + "2"`? Is it the number `3` or the string `"12"`?

In [47]:
a = 1 + "2"
print(a)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

To clear up this ambiguity, we must first convert one of the values to be the same type as the other. Standard types like these can be converted by using the type name as a function:

In [51]:
a = 1 + int("2")
print(a)
a = str(1) + "2"
print(a)

3
12


When converting a string, this will only work if the type you are attempting to convert to is valid.

In [52]:
a = int("2.0")

ValueError: invalid literal for int() with base 10: '2.0'

This does not work because `2.0` is not an integer value. If you instead converted to a `float`, it will work.

In [54]:
a = float("2.0")
print(a)

2.0


In [55]:
a = float("2")
print(a)

2.0


Why did that work? `2` is an integer? Integers are automatically converted to floats as needed in Python 3. (In Python 2 this does not happen in integer division.) This means any of the operations that work on ints and floats will work on a mixture of the two, and the result will always be a float.

You can also convert a `float` to an `int`, this will `floor` the float (round down the decimal to the nearest integer value.

In [59]:
a = int(2.3)
print(a)

2


We've touched on some of the more basic operations we can perform on data, including type conversion, but there are many other operations. Not all operations will make sense for every data type, as we've seen in the case of string subtraction. *Division* (`/`) also generally only makes sense for number types - minor caveat that we will later find that number arrays can also have mathematical operations performed on them. In Python 3, division will always return a float, even when the integer division would not require rounding.

In [57]:
a = 10/2
print(a)

5.0


### length
Because strings are arrays of characters, they have a length, and there is a built-in method to determine their length: `len`.

In [45]:
a = "Hello World!"
print(len(a))

12


What about `int` and `float` types? These are single value data types, so what do you think the `len` method will do?

In [46]:
a = 5
len(a)

TypeError: object of type 'int' has no len()

## Combining variables

We've discussed performing operations directly on values of various types, but what about on variables.

What is the value of `b` that will be printed in this example:

`a = 10
 b = a + 5
 a = 5
 print(b)`

In [58]:
a = 10
b = a + 5
a = 5
print(b)

15


This may be surprising if you are used to working with spreadsheets instead of programming languages. In a spreadsheet, if we make one cell depend on another, changing the latter will change the former as well. So what's happening here?

When we assign `a` the value `10` what are we doing? We are assigning the name `a` to a location in the computer memory where the value `10` is stored. We can think of `a` as a reference (or pointer) to that location. If we change `a`, we are assigning that name to a *different* location in memory where the new value is stored. 

But what are we doing when we say `b = a` or `b = a + 5`? 

We are assigning `b` to the same location in memory as `a` in the first case. In the second case, we are assigning `b` to the location in memory for the *value* resulting from `a + 5`. In either case, when we change `a` this will not change `b` because we are not changing the value `b` references, we are only changing the value `a` references.

**NOTE:** You may have noticed that when working with strings thus far, we have defined them using `'Hello World!'` and `"Hello World!"`. In some languages, single and double quotes do actually create different data types, but they are interchangeable in Python.

# List-like data types

We have already worked with one list-like data type - the `string`: an array of characters - and learned about one operation we can perform on such types - the `len` method to determine the length of the string. We will now explore some of the other operations we can do on these sorts of data types. We will start by listing some of the common list-like data types and then explore some of the methods available, and some of the differences.

List-like data types:
* strings
* tuples
* lists
* numpy arrays

Let's take a look at how to declare these different types, and what we can put in them. For example, strings are declared using single or double quotes around text: `'my string'` or `"my string"`. Only characters can go in strings, but anything symbol or number can be represented as a character, so in principle we can store any type of data as strings, it just won't generally be the most efficient way of doing so. Now we'll explore the other types.

### Tuples

In [79]:
a = (0,1,2,3,4,5)
print(type(a))
print(a)

<class 'tuple'>
(0, 1, 2, 3, 4, 5)


In [88]:
a = ('0','1','2','3','4','5')
print(a)

('0', '1', '2', '3', '4', '5')


In [77]:
a = (0,1,2,3.0,'4.0','5')
print(a)

(0, 1, 2, 3.0, '4.0', '5')


In [113]:
a = ((0,1,2),(3,4),5)
print(a)

((0, 1, 2), (3, 4), 5)



From these examples we have a few takeaways: 
* Tuples are declared using rounded brackets
* Tuples can be filled with any of the standard data types we have learned about so far, or any mixture of those types. In fact, each element of a tuple can be any type, including tuples or even your own methods or classes.

### Lists

In [82]:
a = [0,1,2,3,4,5]
print(type(a))
print(a)

<class 'list'>
[0, 1, 2, 3, 4, 5]


In [83]:
a = ['0','1','2','3','4','5']
print(a)

['0', '1', '2', '3', '4', '5']


In [84]:
a = [0,1,2,3.0,'4.0','5']
print(a)

[0, 1, 2, 3.0, '4.0', '5']


In [85]:
a = [(0,1,2),(3,4,5)]
print(a)

[(0, 1, 2), (3, 4, 5)]


In [112]:
a = [[0,1,2],[3,4],5]
print(a)

[[0, 1, 2], [3, 4], 5]


From these examples the takaways are:
* Lists are declared using square brackets: `[]`
* Lists can also be filled with any of the standard data types we have learned about so far, or any mixture of those types, etc.

### Arrays
In Python, when we talk about arrays, we are talking about a specific implementation: `numpy arrays`. Python does not have a built-in array data type, it uses lists for everything. Lists are very powerful, but because they can contain arbitrary data-types, they are less efficient when it comes to the manipulation of large data sets. Because there is no built in array-type, we hvae to `import` the module/library we wish to use. We will discuss the syntax for importing libraries more in a future section. 

In [89]:
import numpy as np

In [155]:
a = np.array([0,1,2,3,4,5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [153]:
a = np.array([0,1.0,2,3,4.0,5.0])
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5.]
float64


In [109]:
a = np.array(['0','1','2','3','4','5'])
print(a)
print(a.dtype)

['0' '1' '2' '3' '4' '5']
<U1


In [116]:
a = np.array([0,1.0,'2','3','4','5'])
print(a)
print(a.dtype)

['0' '1.0' '2' '3' '4' '5']
<U32


In [151]:
a = np.array([[0,1,2],[3,4,5]])
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2]
 [3 4 5]]
int64
(2, 3)


In [149]:
a = np.array([[0,1,2],[3,4],5])
print(a)
print(a.dtype)
print(a.shape)

[list([0, 1, 2]) list([3, 4]) 5]
object
(3,)


A few notes on some new concepts:
* Properties of the array can be accessed with array.property, i.e. `array.shape` or `array.dtype`:
  * This is how properties of any class are accessed - we will discuss classes more in another lesson
  * `dtype`: this is the type for the elements in the numpy array
  * `shape`: this is a tuple giving the number of rows and columns: if we have an *N*-dimensional array, the lenght of the shape tuple is *N* and each element of the shape tuple givens the length of that dimension.
* New types:
  * `int64`: that simply means that these are 64-bit (8-byte) integers, rather than the 4-byte default
  * `float64`: again, 64-bit floats (double precision) rather than 32-bit. 
  * new string types: here the `U` indicates `unicode`, which is the particular way of encoding symbols and characters, `U1` is a 1-byte `char` - the usual - and `U32` is a 32-bit (4-byte) `char`. This larger size is chosen when floats are represented by strings because floats can generally be much larger in size than single characters.

These examples also leave us with a few take-aways:
* You create a numpy array with the array() method, giving it the input list of elements as an argument to the method.
* Numpy can take any valid list and convert it to a numpy array, however they do have some unique behavior. 
  * If you create a numpy array with a mixture of integers and floats, it will convert all integers to floats. If you create the array with a mixture of strings and numbers, it will convert all elements to strings.
  * Numpy arrays created with a list of lists of the same length will create a multi-dimentional array.
  * Arrays created with a mixture of lists of different lenght and individual numbers will treat each element as an arbitrary `object` type

As we go forward, we will find that many of the numpy array specific methods we encounter only work with arrays of numbers. Generally, it is not useful to use arrays rather than the built-in list type when working with arbitrary object types.

We will now explore some of the methods available for manipulating list-like data types.

## Accessing elements

* An item in a list is called an element. Whenever we treat a string as if it were a list, the string’s elements are its individual characters.
* This works the same way for all list-like data types.
* Elements of a list-like type are accessed using their index (numerical position in the list).
* The list index starts at `0` (unlike in MatLab, or Fortran, where it starts at `1`).
* You can access elements from the end of the list using negitive integers: `-1` is the last element, `-2` second to last, etc.

In [120]:
a = 'Hello World!'
print(a[0])
print(a[6])
print(a[-1])
print(a[-2])

H
W
!
d


In [121]:
a = (0,1,2,3,4,5)
print("first: {}, last: {}".format(a[0],a[-1]))

first: 0, last: 5


In [122]:
a = [0,1,2,3,4,5]
print("first: {}, last: {}".format(a[0],a[-1]))

first: 0, last: 5


In [123]:
a = np.array([0,1,2,3,4,5])
print("first: {}, last: {}".format(a[0],a[-1]))

first: 0, last: 5


## Slicing

* A slice is a part of a a list-like thing.
* We take a slice by using [start:stop], where start is replaced with the index of the first element we want and stop is replaced with the index of the element just after the last element we want.
* Mathematically, you might say that a slice selects [start:stop).
* The difference between stop and start is the slice’s length.
* Taking a slice does not change the contents of the original list-like object. Instead, the slice is a copy of part of the original.
* In the case of strings, a part of a string is called a substring. A substring can be as short as a single character.

In [67]:
a = 'Hello World!'
b = a[0:5]
print(b)
print(a)

Hello
Hello World!


In [126]:
a = [0,1,2,3,4,5]
print(a[0:3])

[0, 1, 2]


* What do you think `a[:4]` will do?
* What does `a[2:]` do?
* What does `a[3:-2]` do?
* What about `a[:]`?

In [128]:
print(a[:4])
print(a[2:])
print(a[3:-2])
print(a[:])

[0, 1, 2, 3]
[2, 3, 4, 5]
[3]
[0, 1, 2, 3, 4, 5]


In [139]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(a)
print(a[3:6])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[]


**What happened?** Why was the sliced array empty?

The numpy array we created has two dimensions:

In [140]:
a.shape

(3, 4)

Neither dimension is longer than 3 entries, so there are not elements in index 3-6.

How do we slice in this multidemensional case? 

First, how do we access elements? Based on the way the `shape` is reported, it's not a bad guess to assume that we can access the row and column index using two comma-separated indices.

What will these return:
* `a[0]`?
* `a[0, 1]`?
* `a[1, 2]`?

In [141]:
print(a[0])
print(a[0, 1])
print(a[1, 2])

[0 1 2 3]
1
6


Slicing will work the same way:

In [143]:
print(a[0:2, 1:3])

[[1 2]
 [5 6]]


## Modifying List-like types

We will now take a minute to explore how to modify or add to the values stored in list-like data types.

We have seen how to access elements from list-like types. Can we change them?

In [187]:
a = [0,1,2]
a[1] = 3
print(a)

[0, 3, 2]


In [188]:
a = (0,1,2)
a[1] = 3
print(a)

TypeError: 'tuple' object does not support item assignment

In [189]:
a = "Hello"
a[0] = 'h'
print(a)

TypeError: 'str' object does not support item assignment

To explore why we are able to assign new values to individual 'items' of the list, but not strings or tuples, lets step back and look again at some of the features of variable assignment we've already discussed.

When discussing types initially we learned about how to add two strings together:

In [193]:
a = "Hello"
b = a + " World!"
print(b)

Hello World!


We can do the same with tuples and lists:

In [178]:
a = (0,1,2)
b = a + (3,4,5)
print(b)

(0, 1, 2, 3, 4, 5)


In [192]:
a = [0,1,2]
b = a + [3,4,5]
print(b)

[0, 1, 2, 3, 4, 5]


Now, in our discussion of creating new variables that depend on previously defined variables, following the example above, we learned that once you define `b`, you can change `a` and it will not change `b`. Why?

In [170]:
a = "Hello World!"
b = a
a = "Goodbye World!"
print(b)

Hello World!


Again, this is because when we say `b = a` we are telling `b` to reference the same location in memory that `a` is currently references where the value `Hello World!` is being stored. When we change `a` we are not changing the value in memory that `b` is referencing, we are telling `a` to references a different location in memory, where the new value, `Goodbye World!` is being stored.

The same is true for tuples:

In [171]:
a = (0,1,2)
b = a
a = (3,4,5)
print(b)

(0, 1, 2)


Now let's try lists:

In [172]:
a = [0,1,2]
b = a
a = [3,4,5]
print(b)

[0, 1, 2]


So far so good, but in all of these cases we set `a` equal to a new value, meaning we changed the location in memory that `a` is referencing. However, we learned above that we can change individual elements of a list, what happens if we only change part of `a`?

In [173]:
a = [0,1,2]
b = a
a[0] = 3
print(b)

[3, 1, 2]


Now `b` did change! What's going on?

## Mutable and Immutable types

In the example above, when we changed only a part of list `a`, we actually changed the values being stored in the location in memory that `a` references. The line `b = a` created the variable `b` as a reference to the *same memory location* as `a`. So, when we change the values being stored at that memory location using `a` as the reference, `b` also changes. This is a fundamental property of **mutable** data types. Lists are **mutable**, meaning that the data the list, or any mutable type, stores can be changed. 

Numbers are an example of an **immutable** type, meaning you cannot change the data. This seems obvious in this case. If you say `a = 2`, so `a` is a reference to the value `2`, you cannot change `2`, `2` is always `2`. All you can do is change `a` to reference a different value. This is also true for strings and tuples: they **immutable**. This is why even though we can access individual elements of strings and tuples, we cannot change those elements. Once a string or tuple is created, that string or tuple value cannot be changed. You instead have to tell your variable to reference a new string value.

So how do we make variables with mutable values independent?

In [194]:
a = [0,1,2]
b = list(a)
a[0] = 3
print(b)

[0, 1, 2]


Here we used the `list` function to make a copy of list `a` - a new memory location - that the new variable `b` is now references. So now when we change `a` that does not change `b`: they are not referencing the same memory location in this case.

**Bonus question:** We said that to change a variable with an immutable value, we have to set it equal to a different value, meaning it now references a different memory location on the computer. What happens to the old value that no-longer has a variable to reference it?

## Functions and Methods

A function is a block of code which only runs when it is called. You can pass data, into a function and a function can return data as a result.

### Built-in Functions
We've already seen several examples of functions: `print`, `len`, `type`, and even the `int`, `float`, and `string` functions that changed an existing value from one type to another. These are all built-in functions (meaning they are part of the basic Python interpreter and do not require the `import` of a particular library) that apply broadly, although `len` only applies to list-like types.

Here are a few general rules about functions:
* an *argument* is a value passed into a function
* Functions can take zero arguments
* To call a function, you must use round brackets, even if you give no arguments, so that Python knows a function is being called: `(<argument>)`
* Functions can take multiple arguments, separated by commas: `function(arg1, arg2, ...)`
* Functions always return a value. If no return value is provided within the function code block, it will return None

### Creating functions
We will encounter more advanced features of functions as we go forward, but the basic syntax for defining your own function is:

In [163]:
def my_function(my_name):
    print("This is {}'s function!".format(my_name))

my_function("Dr. Hanks")

This is Dr. Hanks's function!


### Methods

Methods are a particular type of function which is associated with a specific object (or class) and can only be called on that object: in other words methods are functions that belong to objects. Methods also have access to the data stored by the object, and in some cases can be used to modify that data, while in general Functions cannot modify the data stored by an object.

#### List-like type methods

All of the built-in list-like types in Python have a few fundamental methods in common:
* `count()`: returns the number of times a specified value occurs
* `index()`: returns the index for the first element with the specified value

In [198]:
a = "Hello World!"
print(a.count('o'))
print(a.index('r'))

2
8


In [202]:
a = (0,0,1,1,2,3,3,3,4)
print(a.count(3))
print(a.index(2))

3
4


Because tuples are immutable, these are the only methods available. These methods access the data stored in the tuple, but do not attempt to modify that data. Strings are also limited, but many text-editing related methods exist for string objects, the key point is that they all *return a new string*. 

For example, the `capitalize()` method capitalizes the first letter of a string, which sounds like it changes the string, let's give it a try:

In [207]:
a = "hello World!"
print(a.capitalize())

Hello world!


In [208]:
print(a)

hello World!


#### List methods
Lists are mutable, so there are many more things we can do with lists to manipulate their data in useful ways. 
* `append()`: adds single values to the end of a list
* `extend()`: adds the elements of any list-like type to the end of the current list
* `sort()`: sorts the list
* `pop()`: removes the element at the specified position

And more. In Jupyter, or iPython, you can see all of the available methods by typing the name of your list variable followed by a dot to indicate that you want to use a list method and hitting tab.

In [212]:
a = [0,1,2]
print(a)
a.append(3)
print(a)

[0, 1, 2]
[0, 1, 2, 3]


In [213]:
b = [4,5,6]
b.extend(a)
print(b)

[4, 5, 6, 0, 1, 2, 3]


In [214]:
b.sort()
print(b)

[0, 1, 2, 3, 4, 5, 6]


In [215]:
b.pop(-1)
print(b)

[0, 1, 2, 3, 4, 5]


#### Numpy functions

In data analysis, a helpful feature of numpy arrays is that common mathematical operations can be performed on them and the operation will be done element-by-element without you as the programmer having to access each element directly.

In [226]:
a = np.array([1,1.5,2,2.5,3,3.5,4,4.5,5])
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [227]:
print(a * 2)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [228]:
print(a + 10)

[11.  11.5 12.  12.5 13.  13.5 14.  14.5 15. ]


In [229]:
print(a - 2)

[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]


In [230]:
print(a/5)

[0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


The Numpy library is also contains many functions that allow us to perform a variety of calculations on the array or on only one dimension (axis) of the array, allowing for rapid manipulation of large data sets.

In [225]:
print(np.mean(a))

3.0


In [231]:
print(np.max(a))

5.0


In [232]:
print(np.min(a))

1.0


In [233]:
print(np.sqrt(a))

[1.         1.22474487 1.41421356 1.58113883 1.73205081 1.87082869
 2.         2.12132034 2.23606798]


In [236]:
a2 = np.array([[0,0.5,1,1.5,2,2.5,3,3.5,4,4.5],[5,5.5,6.,6.5,7,7.5,8,8.5,9,9.5]])
print(a2)

[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]]


In [237]:
print(np.sqrt(a2))

[[0.         0.70710678 1.         1.22474487 1.41421356 1.58113883
  1.73205081 1.87082869 2.         2.12132034]
 [2.23606798 2.34520788 2.44948974 2.54950976 2.64575131 2.73861279
  2.82842712 2.91547595 3.         3.082207  ]]


In [238]:
print(np.max(a2))

9.5


In [242]:
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[4.5 9.5]


In [243]:
print(np.sum(a2))

95.0


In [244]:
print(np.sum(a2,axis=0))
print(np.sum(a2,axis=1))

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[22.5 72.5]


## Repeated actions with loops

### For loops

A *For loop* allows you to execute a command once for each value in a collection