In [156]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [180]:
data = pd.read_csv('/Users/alihanks/dosenet_data/etch_roof.csv')
data

deviceTime_utc           deviceTime_local  deviceTime_unix  \
0       2019-08-10 16:55:46+00:00  2019-08-10 09:55:46-07:00       1565456146   
1       2019-08-10 16:50:46+00:00  2019-08-10 09:50:46-07:00       1565455846   
2       2019-08-10 16:45:46+00:00  2019-08-10 09:45:46-07:00       1565455546   
3       2019-08-10 16:40:46+00:00  2019-08-10 09:40:46-07:00       1565455246   
4       2019-08-10 16:35:46+00:00  2019-08-10 09:35:46-07:00       1565454946   
5       2019-08-10 16:30:46+00:00  2019-08-10 09:30:46-07:00       1565454646   
6       2019-08-10 16:25:46+00:00  2019-08-10 09:25:46-07:00       1565454346   
7       2019-08-10 16:20:46+00:00  2019-08-10 09:20:46-07:00       1565454046   
8       2019-08-10 16:15:46+00:00  2019-08-10 09:15:46-07:00       1565453746   
9       2019-08-10 16:10:46+00:00  2019-08-10 09:10:46-07:00       1565453446   
10      2019-08-10 16:05:46+00:00  2019-08-10 09:05:46-07:00       1565453146   
11      2019-08-10 16:00:46+00:00  2019-08-10 09:00:46-07:00       1565452846   
12      2019-08-10 15:55:46+00:00  2019-08-10 08:55:46-07:00       1565452546   
13      2019-08-10 15:50:46+00:00  2019-08-10 08:50:46-07:00       1565452246   
14      2019-08-10 15:45:46+00:00  2019-08-10 08:45:46-07:00       1565451946   
15      2019-08-10 15:40:46+00:00  2019-08-10 08:40:46-07:00       1565451646   
16      2019-08-10 15:35:46+00:00  2019-08-10 08:35:46-07:00       1565451346   
17      2019-08-10 15:30:46+00:00  2019-08-10 08:30:46-07:00       1565451046   
18      2019-08-10 15:25:46+00:00  2019-08-10 08:25:46-07:00       1565450746   
19      2019-08-10 15:20:46+00:00  2019-08-10 08:20:46-07:00       1565450446   
20      2019-08-10 15:15:46+00:00  2019-08-10 08:15:46-07:00       1565450146   
21      2019-08-10 15:10:46+00:00  2019-08-10 08:10:46-07:00       1565449846   
22      2019-08-10 15:05:46+00:00  2019-08-10 08:05:46-07:00       1565449546   
23      2019-08-10 15:00:46+00:00  2019-08-10 08:00:46-07:00       1565449246   
24      2019-08-10 14:55:46+00:00  2019-08-10 07:55:46-07:00       1565448946   
25      2019-08-10 14:50:46+00:00  2019-08-10 07:50:46-07:00       1565448646   
26      2019-08-10 14:45:46+00:00  2019-08-10 07:45:46-07:00       1565448346   
27      2019-08-10 14:40:46+00:00  2019-08-10 07:40:46-07:00       1565448046   
28      2019-08-10 14:35:46+00:00  2019-08-10 07:35:46-07:00       1565447746   
29      2019-08-10 14:30:46+00:00  2019-08-10 07:30:46-07:00       1565447446   
...                           ...                        ...              ...   
306828  2015-11-20 04:52:09+00:00  2015-11-19 20:52:09-08:00       1447995129   
306829  2015-11-20 04:47:08+00:00  2015-11-19 20:47:08-08:00       1447994828   
306830  2015-11-20 04:42:08+00:00  2015-11-19 20:42:08-08:00       1447994528   
306831  2015-11-20 04:37:07+00:00  2015-11-19 20:37:07-08:00       1447994227   
306832  2015-11-20 04:32:07+00:00  2015-11-19 20:32:07-08:00       1447993927   
306833  2015-11-20 04:27:06+00:00  2015-11-19 20:27:06-08:00       1447993626   
306834  2015-11-20 04:22:16+00:00  2015-11-19 20:22:16-08:00       1447993336   
306835  2015-11-20 04:17:15+00:00  2015-11-19 20:17:15-08:00       1447993035   
306836  2015-11-20 04:12:15+00:00  2015-11-19 20:12:15-08:00       1447992735   
306837  2015-11-20 04:07:14+00:00  2015-11-19 20:07:14-08:00       1447992434   
306838  2015-11-20 04:02:14+00:00  2015-11-19 20:02:14-08:00       1447992134   
306839  2015-11-20 03:57:13+00:00  2015-11-19 19:57:13-08:00       1447991833   
306840  2015-11-20 03:52:13+00:00  2015-11-19 19:52:13-08:00       1447991533   
306841  2015-11-20 03:47:12+00:00  2015-11-19 19:47:12-08:00       1447991232   
306842  2015-11-20 03:42:12+00:00  2015-11-19 19:42:12-08:00       1447990932   
306843  2015-11-20 03:37:11+00:00  2015-11-19 19:37:11-08:00       1447990631   
306844  2015-11-20 03:32:11+00:00  2015-11-19 19:32:11-08:00       1447990331   
306845  2015-11-20 03:27:10+00:00  2015-11-19 19:2

In [181]:
print(data.describe())

       deviceTime_unix            cpm       cpmError
count     3.068580e+05  306858.000000  306858.000000
mean      1.502707e+09       2.660846       0.722205
std       3.358637e+07       0.739751       0.103020
min       1.447986e+09       0.000000       0.000000
25%       1.471995e+09       2.200000       0.663325
50%       1.496966e+09       2.600000       0.721110
75%       1.532671e+09       3.200000       0.800000
max       1.565456e+09       8.600000       2.828430


In [187]:
cpm_data = data.loc[:,"deviceTime_local":"cpmError"]
cpm_data = cpm_data.drop(["deviceTime_unix"],axis=1)
cpm_data

deviceTime_local  cpm  cpmError
0       2019-08-10 09:55:46-07:00  2.6  0.721110
1       2019-08-10 09:50:46-07:00  3.2  0.800000
2       2019-08-10 09:45:46-07:00  1.6  0.565685
3       2019-08-10 09:40:46-07:00  3.2  0.800000
4       2019-08-10 09:35:46-07:00  3.2  0.800000
5       2019-08-10 09:30:46-07:00  2.2  0.663325
6       2019-08-10 09:25:46-07:00  2.6  0.721110
7       2019-08-10 09:20:46-07:00  2.2  0.663325
8       2019-08-10 09:15:46-07:00  2.2  0.663325
9       2019-08-10 09:10:46-07:00  2.2  0.663325
10      2019-08-10 09:05:46-07:00  2.0  0.632456
11      2019-08-10 09:00:46-07:00  2.8  0.748331
12      2019-08-10 08:55:46-07:00  3.6  0.848528
13      2019-08-10 08:50:46-07:00  3.4  0.824621
14      2019-08-10 08:45:46-07:00  2.0  0.632456
15      2019-08-10 08:40:46-07:00  3.4  0.824621
16      2019-08-10 08:35:46-07:00  2.4  0.692820
17      2019-08-10 08:30:46-07:00  2.4  0.692820
18      2019-08-10 08:25:46-07:00  2.0  0.632456
19      2019-08-10 08:20:46-07:00  2.2  0.663325
20      2019-08-10 08:15:46-07:00  2.8  0.748331
21      2019-08-10 08:10:46-07:00  3.6  0.848528
22      2019-08-10 08:05:46-07:00  3.4  0.824621
23      2019-08-10 08:00:46-07:00  4.2  0.916515
24      2019-08-10 07:55:46-07:00  2.6  0.721110
25      2019-08-10 07:50:46-07:00  3.4  0.824621
26      2019-08-10 07:45:46-07:00  3.4  0.824621
27      2019-08-10 07:40:46-07:00  3.2  0.800000
28      2019-08-10 07:35:46-07:00  2.8  0.748331
29      2019-08-10 07:30:46-07:00  3.4  0.824621
...                           ...  ...       ...
306828  2015-11-19 20:52:09-08:00  3.4  0.824621
306829  2015-11-19 20:47:08-08:00  1.8  0.600000
306830  2015-11-19 20:42:08-08:00  2.4  0.692820
306831  2015-11-19 20:37:07-08:00  2.2  0.663325
306832  2015-11-19 20:32:07-08:00  2.4  0.692820
306833  2015-11-19 20:27:06-08:00  4.0  0.894427
306834  2015-11-19 20:22:16-08:00  2.8  0.748331
306835  2015-11-19 20:17:15-08:00  3.0  0.774597
306836  2015-11-19 20:12:15-08:00  2.8  0.748331
306837  2015-11-19 20:07:14-08:00  2.2  0.663325
306838  2015-11-19 20:02:14-08:00  3.2  0.800000
306839  2015-11-19 19:57:13-08:00  2.6  0.721110
306840  2015-11-19 19:52:13-08:00  4.4  0.938083
306841  2015-11-19 19:47:12-08:00  1.8  0.600000
306842  2015-11-19 19:42:12-08:00  2.8  0.748331
306843  2015-11-19 19:37:11-08:00  2.2  0.663325
306844  2015-11-19 19:32:11-08:00  3.4  0.824621
306845  2015-11-19 19:27:10-08:00  1.4  0.529150
306846  2015-11-19 19:22:10-08:00  2.4  0.692820
306847  2015-11-19 19:17:09-08:00  1.4  0.529150
306848  2015-11-19 19:12:08-08:00  2.8  0.748331
306849  2015-11-19 19:07:08-08:00  1.8  0.600000
306850  2015-11-19 19:02:07-08:00  3.0  0.774597
306851  2015-11-19 18:57:07-08:00  3.2  0.800000
306852  2015-11-19 18:52:16-08:00  1.8  0.600000
306853  2015-11-19 18:47:16-08:00  3.4  0.824621
306854  2015-11-19 18:42:15-08:00  2.4  0.692820
306855  2015-11-19 18:37:15-08:00  3.4  0.824621
306856  2015-11-19 18:32:13-08:00  2.8  0.748331
306857  2015-11-19 18:27:13-08:00  4.0  0.894427

[306858 rows x 3 columns]

In [188]:
print(cpm_data.max())
print(cpm_data.min())

deviceTime_local    2019-08-10 09:55:46-07:00
cpm                                       8.6
cpmError                              2.82843
dtype: object
deviceTime_local    2015-11-19 18:27:13-08:00
cpm                                         0
cpmError                                    0
dtype: object


In [190]:
cpm_data.loc[:,"cpm"] > 0.0

0         True
1         True
2         True
3         True
4         True
5         True
6         True
7         True
8         True
9         True
10        True
11        True
12        True
13        True
14        True
15        True
16        True
17        True
18        True
19        True
20        True
21        True
22        True
23        True
24        True
25        True
26        True
27        True
28        True
29        True
          ... 
306828    True
306829    True
306830    True
306831    True
306832    True
306833    True
306834    True
306835    True
306836    True
306837    True
306838    True
306839    True
306840    True
306841    True
306842    True
306843    True
306844    True
306845    True
306846    True
306847    True
306848    True
306849    True
306850    True
306851    True
306852    True
306853    True
306854    True
306855    True
306856    True
306857    True
Name: cpm, Length: 306858, dtype: bool

In [191]:
mask = cpm_data["cpm"] > 0.0
cpm_data[mask]

deviceTime_local  cpm  cpmError
0       2019-08-10 09:55:46-07:00  2.6  0.721110
1       2019-08-10 09:50:46-07:00  3.2  0.800000
2       2019-08-10 09:45:46-07:00  1.6  0.565685
3       2019-08-10 09:40:46-07:00  3.2  0.800000
4       2019-08-10 09:35:46-07:00  3.2  0.800000
5       2019-08-10 09:30:46-07:00  2.2  0.663325
6       2019-08-10 09:25:46-07:00  2.6  0.721110
7       2019-08-10 09:20:46-07:00  2.2  0.663325
8       2019-08-10 09:15:46-07:00  2.2  0.663325
9       2019-08-10 09:10:46-07:00  2.2  0.663325
10      2019-08-10 09:05:46-07:00  2.0  0.632456
11      2019-08-10 09:00:46-07:00  2.8  0.748331
12      2019-08-10 08:55:46-07:00  3.6  0.848528
13      2019-08-10 08:50:46-07:00  3.4  0.824621
14      2019-08-10 08:45:46-07:00  2.0  0.632456
15      2019-08-10 08:40:46-07:00  3.4  0.824621
16      2019-08-10 08:35:46-07:00  2.4  0.692820
17      2019-08-10 08:30:46-07:00  2.4  0.692820
18      2019-08-10 08:25:46-07:00  2.0  0.632456
19      2019-08-10 08:20:46-07:00  2.2  0.663325
20      2019-08-10 08:15:46-07:00  2.8  0.748331
21      2019-08-10 08:10:46-07:00  3.6  0.848528
22      2019-08-10 08:05:46-07:00  3.4  0.824621
23      2019-08-10 08:00:46-07:00  4.2  0.916515
24      2019-08-10 07:55:46-07:00  2.6  0.721110
25      2019-08-10 07:50:46-07:00  3.4  0.824621
26      2019-08-10 07:45:46-07:00  3.4  0.824621
27      2019-08-10 07:40:46-07:00  3.2  0.800000
28      2019-08-10 07:35:46-07:00  2.8  0.748331
29      2019-08-10 07:30:46-07:00  3.4  0.824621
...                           ...  ...       ...
306828  2015-11-19 20:52:09-08:00  3.4  0.824621
306829  2015-11-19 20:47:08-08:00  1.8  0.600000
306830  2015-11-19 20:42:08-08:00  2.4  0.692820
306831  2015-11-19 20:37:07-08:00  2.2  0.663325
306832  2015-11-19 20:32:07-08:00  2.4  0.692820
306833  2015-11-19 20:27:06-08:00  4.0  0.894427
306834  2015-11-19 20:22:16-08:00  2.8  0.748331
306835  2015-11-19 20:17:15-08:00  3.0  0.774597
306836  2015-11-19 20:12:15-08:00  2.8  0.748331
306837  2015-11-19 20:07:14-08:00  2.2  0.663325
306838  2015-11-19 20:02:14-08:00  3.2  0.800000
306839  2015-11-19 19:57:13-08:00  2.6  0.721110
306840  2015-11-19 19:52:13-08:00  4.4  0.938083
306841  2015-11-19 19:47:12-08:00  1.8  0.600000
306842  2015-11-19 19:42:12-08:00  2.8  0.748331
306843  2015-11-19 19:37:11-08:00  2.2  0.663325
306844  2015-11-19 19:32:11-08:00  3.4  0.824621
306845  2015-11-19 19:27:10-08:00  1.4  0.529150
306846  2015-11-19 19:22:10-08:00  2.4  0.692820
306847  2015-11-19 19:17:09-08:00  1.4  0.529150
306848  2015-11-19 19:12:08-08:00  2.8  0.748331
306849  2015-11-19 19:07:08-08:00  1.8  0.600000
306850  2015-11-19 19:02:07-08:00  3.0  0.774597
306851  2015-11-19 18:57:07-08:00  3.2  0.800000
306852  2015-11-19 18:52:16-08:00  1.8  0.600000
306853  2015-11-19 18:47:16-08:00  3.4  0.824621
306854  2015-11-19 18:42:15-08:00  2.4  0.692820
306855  2015-11-19 18:37:15-08:00  3.4  0.824621
306856  2015-11-19 18:32:13-08:00  2.8  0.748331
306857  2015-11-19 18:27:13-08:00  4.0  0.894427

[306857 rows x 3 columns]

In [192]:
good_cpm_data = cpm_data[mask]

In [203]:
time_mask = good_cpm_data['deviceTime_local']>'2019-08-05 00:00:00-07:00'
month_cpm = good_cpm_data[time_mask]
print(month_cpm)

               deviceTime_local  cpm  cpmError
0     2019-08-10 09:55:46-07:00  2.6  0.721110
1     2019-08-10 09:50:46-07:00  3.2  0.800000
2     2019-08-10 09:45:46-07:00  1.6  0.565685
3     2019-08-10 09:40:46-07:00  3.2  0.800000
4     2019-08-10 09:35:46-07:00  3.2  0.800000
5     2019-08-10 09:30:46-07:00  2.2  0.663325
6     2019-08-10 09:25:46-07:00  2.6  0.721110
7     2019-08-10 09:20:46-07:00  2.2  0.663325
8     2019-08-10 09:15:46-07:00  2.2  0.663325
9     2019-08-10 09:10:46-07:00  2.2  0.663325
10    2019-08-10 09:05:46-07:00  2.0  0.632456
11    2019-08-10 09:00:46-07:00  2.8  0.748331
12    2019-08-10 08:55:46-07:00  3.6  0.848528
13    2019-08-10 08:50:46-07:00  3.4  0.824621
14    2019-08-10 08:45:46-07:00  2.0  0.632456
15    2019-08-10 08:40:46-07:00  3.4  0.824621
16    2019-08-10 08:35:46-07:00  2.4  0.692820
17    2019-08-10 08:30:46-07:00  2.4  0.692820
18    2019-08-10 08:25:46-07:00  2.0  0.632456
19    2019-08-10 08:20:46-07:00  2.2  0.663325
20    2019-08

In [207]:
import plotly.express as px
import plotly.graph_objects as go

In [209]:
#fig = px.scatter(month_cpm,x="deviceTime_local",y="cpm",error_y="cpmError")
fig = go.Figure(go.Scatter(x=month_cpm["deviceTime_local"].values, 
            y=month_cpm["cpm"].values,
            error_y=dict(
                type='data',
                symmetric=True,
                array=month_cpm["cpmError"].values)
))
fig.show()

# Variables

Variables are symbolic names associated with information, values, which are paired with storage locations on the computer. In other words, if you wish to be able to access a piece of information, you store that information in memory and access it using this symbolic name, the variable, that has been linked to that location.

We assign values to variables using the `=` opperator.

In [117]:
# Let's define variables to store the number of students in the class and the name of the course
i = 5
a = 'Engineering 11'

### Variable names:
* They can **only** contain letters, digits, or underscores `_`
* They **cannot** start with digits
* Variable names that start with underscores like `__special` have a special meaning and should be avoided until you understand the convention.

### Displaying variable values
You can display these values using the built-in python function, `print`, that prints things as text. To do this:
* Call the function (i.e., tell Python to run it) by using its name
* Provide values to the function (i.e., the things to print) in parentheses
* The values passed to the function are called **arguments**

In [118]:
print(a)

Engineering 11


### Formatting strings
To add text to your print statment, use a string formatting method. For example:

In [119]:
print("i = {}".format(i))
print("{} has {} students".format(a,i))
print("{1} has {0} students".format(i,a))

i = 5
Engineering 11 has 5 students
Engineering 11 has 5 students


# Accessing variables

In [4]:
print(b)

NameError: name 'b' is not defined

**Why did this fail?**

The variable `b` was not previously defined. It must be defined - created - before we can use it.

## Accessing variables
You might have noticed that we were able to use the variables `i` and `a` across cells. 

During a single interactive session, or jupyter notebook, variables persist - maintain their most recent memory location pairing and assigned value - beyond the cell (individual *code block*) they are defined within. 

Another way to say this is that variables defined in this way are *global* in scope. *Scope* is an important concept in programming that we will return to once we have been introduced to the idea of *code blocks*.

# Data types

Values in a program will have a specific **type** which determines the types of operations (methods) that can be performed on that value.

There is a built-in method: `type` which can be used to determine the type of a variable.

In [5]:
a = 5
print(type(a))

<class 'int'>


In [6]:
a = "Hello World!"
print(type(a))

<class 'str'>


In [7]:
a = 5.5
print(type(a))

<class 'float'>


## Common data types
The three examples above cover the three main basic types we will encounter: `int`, `float`, and `string`

### ints
* An `int` is a signed (positive or negative) whole number. 
* Standard ints are 4 bytes, so can range from -2147483648 to 2147483647. 

### ints
**Where does this range come from?**

Let's consider the example of a small int: a small int is 1 byte, meaning it can range from -128 to 127. One byte is 8 bits (a bit holding a binary value 0 or 1), so there are 7 bits for the integer value - allowing the max value $2^7$ - and one bit for the sign.

### floats
* A `float` is a floating point (real) number, which can have fractional or decimal values. 
* Mathematically, there are an infinite number of real numbers. 
* In computing, the `float` type has to have a finite size, usually 4 bytes, so by definition there will be a finite set of numbers that can be expressed this way. 

### floats
Generally the range and precision of floats is set using this exact representation form:

`significand x base^exponent`

where the significand is an integer, the length of which sets the precision of the number, and the exponent is also an integer. In computing the base is 2 (binary). The standard 32-bit - single precision - format is 24 bits of precision, 7 bits for the exponent, and one for the sign.

### strings
* A character string, usually called a `string` or `str` is simply text. 
* The more fundamental data type is the `char` - a 1-byte type representing a single letter, number, or symbol. 
* In python, there is no single character type, a single character is simply a string of length one. 

### strings
* A string is a character array, meaning unlike ints and floats it is not a single value. 
  * Although strings are often manipulated as if they were single values, there a few fundamental differences that we will encounter resulting from the non-singular nature of the `string` type. 

### strings
**NOTE:** You may have noticed that when working with strings thus far, we have defined them using either single (`'Hello World!'`) or double (`"Hello World!"`) quotes. In some languages, single and double quotes do actually create different data types, but they are interchangeable in Python.

*However*, the reason to use double (single) quotes some cases is that it allows for single (double) quotes to be included in the text of the string.

In [120]:
a = 'Student's name:'
print(a)

SyntaxError: invalid syntax (<ipython-input-120-f96f3c2cfa7b>, line 1)

In [121]:
a = "Student's name:"
print(a)

Student's name:


In [125]:
a = 'Provide input as: "<user input>"'
print(a)

Provide input as: "<user input>"


### Challenge

How would you create a string that included both single and double quotes in the body of the text?

In [124]:
a = 'Provide student'+"'s name as : "+'"<student name>"'
print(a)

Provide student's name as : "<student name>"


## Assigning type in python

You may have noticed that when checking type in the examples above, I used the variable `a` in each case. Why did this work? We know that `a` is a global variable and we saw that after I assigned `a` the value `5` it was an `int`. 


What type is `a` now?

In [12]:
print(type(a))

<class 'str'>


**Why isn't `a` an `int` any more?**

Because we have assigned `a` to a different value, in this case a `string`.

So, we see that when we assign a value to a variable in Python that sets the type for that variable **but** that type is *not fixed*.  

We can change the type for a variable by assigning it a value of a different type. This is not the case for many languages - in those cases you generally assign the type as part of the variable declaration, e.g. `int a = 5`.

## Operations

A value's type determines what operations can be performed on that value. Some of the most basic operations are things like adding (`+`), subtracting (`-`), and multiplying (`*`).

When talking about numbers, all of these operations seem pretty straight forward, and indeed all are possible for `int` and `float` types.

In [13]:
a = 5+3
print(a)

a = 5-3
print(a)

a = 5*3
print(a)

8
2
15


In [14]:
a = 5.5+3.5
print(a)

a = 5.5-3.5
print(a)

a = 5.5*3.5
print(a)

9.0
2.0
19.25


`strings` are a bit different.

Addition still makes sense, it is simply the concatenation of the strings.

In [15]:
a = 'Hello' + ' ' + 'World!'
print(a)

Hello World!


Multiplication can be thought of as repeated addition. So multiplying a string by an integer *N* will simply create a new string consisting of the original string repeated *N* times.

In [16]:
a = '-' * 10
print(a)

----------


Subtraction is less obvious. A string is an array of characters, subtracting one string from another is not a simple process that would always work the same way. For example, how would we interpret `'Hello World!' - 'l'`? There are three `l` characters in the first string, which should we remove? Let's try anyway:

In [17]:
a = 'Hello World!' - 'l'

TypeError: unsupported operand type(s) for -: 'str' and 'str'

## Mixing types and type conversion

What about performing operations that mix types? 

**What would it mean to add a number and a string?**

For example, how should we interpret `1 + "2"`? Is it the number `3` or the string `"12"`?

In [18]:
a = 1 + "2"
print(a)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

### Converting to/from string
To clear up this ambiguity, we must first convert one of the values to be the same type as the other. Standard types like these can be converted by using the type name as a function:

In [19]:
a = 1 + int("2")
print(a)
a = str(1) + "2"
print(a)

3
12


### Converting from string
**NOTE:** When converting a string, this will only work if the type you are attempting to convert to is valid.

In [20]:
a = int("2.0")

ValueError: invalid literal for int() with base 10: '2.0'

**Why didn't this work?**

This does not work because `2.0` is not an integer value. If you instead converted to a `float`, it will work.

In [21]:
a = float("2.0")
print(a)

2.0


**What about the reverse: casting a string `int` to a `float`?**

In [22]:
a = float("2")
print(a)

2.0


**Why did that work?** 

`2` is an integer. Integers are automatically converted to floats as needed in Python 3. This means any of the operations that work on ints and floats will work on a mixture of the two, and the result will always be a float.

In [23]:
a = 3 + 5.5
print(a)

8.5


You can also convert a `float` to an `int`, this will `floor` the float (round down the decimal to the nearest integer value.

In [24]:
a = int(2.3)
print(a)

2


## A few more operations

We've touched on some of the more basic operations we can perform on data, including type conversion, but there are many other operations. Not all operations will make sense for every data type, as we've seen in the case of string subtraction.  

*Division* (`/`) also generally only makes sense for number types 
* minor caveat: we will later see that number arrays can also have mathematical operations performed on them. *

**NOTE:** in Python 3, division will always return a float, even when the integer division would not require rounding.  

In [25]:
a = 10/2
print(a)

5.0


Another useful numerical operation is getting the remainder, this can be done with `%`. This will return the same numerical type as the input: again, if you mix floats and ints the result will be a float.

In [26]:
a = 10%3
print(a)

1


### Determining length
Because strings are arrays of characters, they have a length, and there is a built-in method to determine their length: `len`.

This method actually works on any list-like type: more on this later.

In [27]:
a = "Hello World!"
print(len(a))

12


**What about `int` and `float` types? These are single value data types, so what do you think the `len` method will do?**

In [28]:
a = 5
len(a)

TypeError: object of type 'int' has no len()

In [29]:
a = 5.5
len(a)

TypeError: object of type 'float' has no len()

## Combining variables

We've discussed performing operations directly on values of various types, but what about on variables.

What is the value of `b` that will be printed in this example:

In [30]:
a = 10
b = a + 5
a = 5
print(b)

15


**`b` didn't change when we changed `a`!**  

This may be surprising if you are used to working with spreadsheets instead of programming languages. In a spreadsheet, if we make one cell depend on another, changing the latter will change the former as well. So what's happening here?

**When we assign `a` the value `10` what are we doing?**

We are assigning the name `a` to a location in the computer memory where the value `10` is stored. We can think of `a` as a reference (or pointer) to that location. If we change `a`, we are assigning that name to a *different* location in memory where the new value is stored. 

**But what are we doing when we say `b = a` or `b = a + 5`?**

In the first case, we are assigning `b` to the same location in memory as `a`. In the second case, we are assigning `b` to the location in memory for the *value* resulting from `a + 5`. 

**NOTE:** You can also think of this as: we are putting the value resulting from `a+5` into a location in memory that was previously unused, and `b` is referencing that new location. From our perspective, these are the same thing.

In either case, when we change `a` this will not change `b` because we are not changing the value `b` references, we are only changing the value `a` references.

# List-like data types

We have already worked with one list-like data type - the `string`: an array of characters - and learned about one operation we can perform on such types - the `len` method to determine the length of the string. We will now explore some of the other operations we can do on these sorts of data types. We will start by listing some of the common list-like data types and then explore some of the methods available, and some of the differences.

List-like data types:
* strings
* tuples
* lists
* numpy arrays

Let's take a look at how to declare these different types, and what we can put in them. For example, strings are declared using single or double quotes around text: `'my string'` or `"my string"`. Only characters can go in strings, but anyt symbol or number can be represented as a character, so in principle we can store any type of data as strings, it just won't generally be the most efficient way of doing so. Now we'll explore the other types.

### Tuples

In [31]:
a = (0,1,2,3,4,5)
print(type(a))
print(a)

<class 'tuple'>
(0, 1, 2, 3, 4, 5)


In [32]:
a = ('0','1','2','3','4','5')
print(a)

('0', '1', '2', '3', '4', '5')


In [33]:
a = (0,1,2,3.0,'4.0','5')
print(a)

(0, 1, 2, 3.0, '4.0', '5')


In [34]:
a = ((0,1,2),(3,4),5)
print(a)

((0, 1, 2), (3, 4), 5)


From these examples we have a few takeaways: 
* Tuples are declared using rounded brackets
* Tuples can be filled with any of the standard data types we have learned about so far, or any mixture of those types. In fact, each element of a tuple can be any type, including tuples or even your own methods or classes.

### Lists

In [35]:
a = [0,1,2,3,4,5]
print(type(a))
print(a)

<class 'list'>
[0, 1, 2, 3, 4, 5]


In [36]:
a = ['0','1','2','3','4','5']
print(a)

['0', '1', '2', '3', '4', '5']


In [37]:
a = [0,1,2,3.0,'4.0','5']
print(a)

[0, 1, 2, 3.0, '4.0', '5']


In [38]:
a = [(0,1,2),(3,4,5)]
print(a)

[(0, 1, 2), (3, 4, 5)]


In [39]:
a = [[0,1,2],[3,4],5]
print(a)

[[0, 1, 2], [3, 4], 5]


From these examples the takaways are:
* Lists are declared using square brackets: `[]`
* Lists can also be filled with any of the standard data types we have learned about so far, or any mixture of those types, etc.

### Arrays
In Python, when we talk about arrays, we are talking about a specific implementation: `numpy arrays`. Python does not have a built-in array data type, it uses lists for everything. Lists are very powerful, but because they can contain arbitrary data-types, they are less efficient when it comes to the manipulation of large data sets. Because there is no built in array-type, we hvae to `import` the module/library we wish to use. We will discuss the syntax for importing libraries more in a future section. 

In [40]:
import numpy as np

In [41]:
a = np.array([0,1,2,3,4,5])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [42]:
a = np.array([0,1.0,2,3,4.0,5.0])
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5.]
float64


In [43]:
a = np.array(['0','1','2','3','4','5'])
print(a)
print(a.dtype)

['0' '1' '2' '3' '4' '5']
<U1


In [44]:
a = np.array([0,1.0,'2','3','4','5'])
print(a)
print(a.dtype)

['0' '1.0' '2' '3' '4' '5']
<U32


In [45]:
a = np.array([[0,1,2],[3,4,5]])
print(a)
print(a.dtype)
print(a.shape)

[[0 1 2]
 [3 4 5]]
int64
(2, 3)


In [46]:
a = np.array([[0,1,2],[3,4],5])
print(a)
print(a.dtype)
print(a.shape)

[list([0, 1, 2]) list([3, 4]) 5]
object
(3,)


A few notes on some new concepts:
* Properties of the array can be accessed with array.property, i.e. `array.shape` or `array.dtype`:
  * This is how properties of any class are accessed - we will discuss classes more in another lesson
  * `dtype`: this is the type for the elements in the numpy array
  * `shape`: this is a tuple giving the number of rows and columns: if we have an *N*-dimensional array, the lenght of the shape tuple is *N* and each element of the shape tuple givens the length of that dimension.

* New types:
  * `int64`: that simply means that these are 64-bit (8-byte) integers, rather than the 4-byte default
  * `float64`: again, 64-bit floats (double precision) rather than 32-bit. 
  * new string types: here the `U` indicates `unicode`, which is the particular way of encoding symbols and characters, `U1` is a 1-byte `char` - the usual - and `U32` is a 32-bit (4-byte) `char`. This larger size is chosen when floats are represented by strings because floats can generally be much larger in size than single characters.

These examples also leave us with a few take-aways:
* You create a numpy array with the array() method, giving it the input list of elements as an argument to the method.
* Numpy can take any valid list and convert it to a numpy array, however they do have some unique behavior. 
  * If you create a numpy array with a mixture of integers and floats, it will convert all integers to floats. If you create the array with a mixture of strings and numbers, it will convert all elements to strings.
  * Numpy arrays created with a list of lists of the same length will create a multi-dimentional array.
  * Arrays created with a mixture of lists of different lenght and individual numbers will treat each element as an arbitrary `object` type

As we go forward, we will find that many of the numpy array specific methods we encounter only work with arrays of numbers. Generally, it is not useful to use arrays rather than the built-in list type when working with arbitrary object types.

We will now explore some of the methods available for manipulating list-like data types.

## Accessing elements

* An item in a list is called an element. Whenever we treat a string as if it were a list, the string’s elements are its individual characters.
* This works the same way for all list-like data types.
* Elements of a list-like type are accessed using their index (numerical position in the list).
* The list index starts at `0` (unlike in MatLab, or Fortran, where it starts at `1`).
* You can access elements from the end of the list using negitive integers: `-1` is the last element, `-2` second to last, etc.

In [47]:
a = 'Hello World!'
print(a[0])
print(a[6])
print(a[-1])
print(a[-2])

H
W
!
d


In [48]:
a = (0,1,2,3,4,5)
print("first: {}, last: {}".format(a[0],a[-1]))

first: 0, last: 5


In [49]:
a = [0,1,2,3,4,5]
print("first: {}, last: {}".format(a[0],a[-1]))

first: 0, last: 5


In [50]:
a = np.array([0,1,2,3,4,5])
print("first: {}, last: {}".format(a[0],a[-1]))

first: 0, last: 5


## Slicing

* A slice is a part of a a list-like thing.
* We take a slice by using [start:stop], where start is replaced with the index of the first element we want and stop is replaced with the index of the element just after the last element we want.
* Mathematically, you might say that a slice selects [start:stop).
* The difference between stop and start is the slice’s length.
* Taking a slice does not change the contents of the original list-like object. Instead, the slice is a copy of part of the original.
* In the case of strings, a part of a string is called a substring. A substring can be as short as a single character.

In [51]:
a = 'Hello World!'
b = a[0:5]
print(b)
print(a)

Hello
Hello World!


In [52]:
a = [0,1,2,3,4,5]
print(a[0:3])

[0, 1, 2]


* What do you think `a[:4]` will do?
* What does `a[2:]` do?
* What does `a[3:-2]` do?
* What about `a[:]`?

In [53]:
print(a[:4])
print(a[2:])
print(a[3:-2])
print(a[:])

[0, 1, 2, 3]
[2, 3, 4, 5]
[3]
[0, 1, 2, 3, 4, 5]


In [54]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(a)
print(a[3:6])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[]


**What happened?** Why was the sliced array empty?

The numpy array we created has two dimensions:

In [55]:
a.shape

(3, 4)

Neither dimension is longer than 3 entries, so there are not elements in index 3-6.

**How do we slice in this multidemensional case?**

First, **how do we access elements?** Based on the way the `shape` is reported, it's not a bad guess to assume that we can access the row and column index using two comma-separated indices.

What will these return:
* `a[0]`?
* `a[0, 1]`?
* `a[1, 2]`?

In [56]:
print(a[0])
print(a[0, 1])
print(a[1, 2])

[0 1 2 3]
1
6


Slicing will work the same way:

In [57]:
print(a[0:2, 1:3])

[[1 2]
 [5 6]]


## Modifying List-like types

We will now take a minute to explore how to modify or add to the values stored in list-like data types.

We have seen how to access elements from list-like types. **Can we change them?**

In [58]:
a = [0,1,2]
a[1] = 3
print(a)

[0, 3, 2]


In [59]:
a = (0,1,2)
a[1] = 3
print(a)

TypeError: 'tuple' object does not support item assignment

In [60]:
a = "Hello"
a[0] = 'h'
print(a)

TypeError: 'str' object does not support item assignment

To explore why we are able to assign new values to individual 'items' of the list, but not strings or tuples, lets step back and look again at some of the features of variable assignment we've already discussed.

When discussing types initially we learned about how to add two strings together:

In [61]:
a = "Hello"
b = a + " World!"
print(b)

Hello World!


We can do the same with tuples and lists:

In [62]:
a = (0,1,2)
b = a + (3,4,5)
print(b)

(0, 1, 2, 3, 4, 5)


In [63]:
a = [0,1,2]
b = a + [3,4,5]
print(b)

[0, 1, 2, 3, 4, 5]


Now, in our discussion of creating new variables that depend on previously defined variables, following the example above, we learned that once you define `b`, you can change `a` and it will not change `b`. **Why?**

In [64]:
a = "Hello World!"
b = a
a = "Goodbye World!"
print(b)

Hello World!


Again, this is because when we say `b = a` we are telling `b` to reference the same location in memory that `a` is currently references where the value `Hello World!` is being stored. When we change `a` we are not changing the value in memory that `b` is referencing, we are telling `a` to references a different location in memory, where the new value, `Goodbye World!` is being stored.

The same is true for tuples:

In [65]:
a = (0,1,2)
b = a
a = (3,4,5)
print(b)

(0, 1, 2)


Now let's try lists:

In [66]:
a = [0,1,2]
b = a
a = [3,4,5]
print(b)

[0, 1, 2]


So far so good, but in all of these cases we set `a` equal to a new value, meaning we changed the location in memory that `a` is referencing. However, we learned above that we can change individual elements of a list, **what happens if we only change part of `a`?**

In [67]:
a = [0,1,2]
b = a
a[0] = 3
print(b)

[3, 1, 2]


**Now `b` did change! What's going on?**

## Mutable and Immutable types

In the example above, when we changed only a part of list `a`, we actually changed the values being stored in the location in memory that `a` references. The line `b = a` created the variable `b` as a reference to the *same memory location* as `a`. So, when we change the values being stored at that memory location using `a` as the reference, `b` also changes. This is a fundamental property of **mutable** data types. Lists are **mutable**, meaning that the data the list, or any mutable type, stores can be changed. 

Numbers are an example of an **immutable** type, meaning you cannot change the data. This seems obvious in this case. If you say `a = 2`, so `a` is a reference to the value `2`, you cannot change `2`, `2` is always `2`. All you can do is change `a` to reference a different value. This is also true for strings and tuples: they **immutable**. This is why even though we can access individual elements of strings and tuples, we cannot change those elements. Once a string or tuple is created, that string or tuple value cannot be changed. You instead have to tell your variable to reference a new string value.

**So how do we make variables with mutable values independent?**

In [68]:
a = [0,1,2]
b = list(a)
a[0] = 3
print(b)

[0, 1, 2]


Here we used the `list` function to make a copy of list `a` - a new memory location - that the new variable `b` is now references. So now when we change `a` that does not change `b`: they are not referencing the same memory location in this case.

**Bonus question:** We said that to change a variable with an immutable value, we have to set it equal to a different value, meaning it now references a different memory location on the computer. What happens to the old value that no-longer has a variable to reference it?

# Functions and Methods

A function is a block of code which only runs when it is called. You can pass data, into a function and a function can return data as a result.

## Built-in Functions
We've already seen several examples of functions: `print`, `len`, `type`, and even the `int`, `float`, and `string` functions that changed an existing value from one type to another. These are all built-in functions (meaning they are part of the basic Python interpreter and do not require the `import` of a particular library) that apply broadly, although `len` only applies to list-like types.

Here are a few general rules about functions:
* an *argument* is a value passed into a function
* Functions can take zero arguments
* To call a function, you must use round brackets, even if you give no arguments, so that Python knows a function is being called: `(<argument>)`
* Functions can take multiple arguments, separated by commas: `function(arg1, arg2, ...)`
* Functions always return a value. If no return value is provided within the function code block, it will return None

## Creating functions
We will encounter more advanced features of functions as we go forward, but the basic syntax for defining a function is:
```
def <function name>(<parameters>):
    body
```
* The function name, like variable names, can be anything. 
* You indicate that you are defining a function with `def`. 
* The colon at the end of the first line indicates the start of a *block* of code, in this case the code block that determines what will happen when the function is used.

When definiting the function, we think of inputs as **parameters** used by the function. When we use (call) the function we give it **arguments**. We make this distinction because the parameters within the body of the function do not have a set type or value - they are placeholders for the particular values that will be used any time the function is used. These parameters also have names that are *local* in scope. 

## What is scope?
Scope describes the region of your code where a variable is defined. A global variable is one accessible anywhere in the code. There are also local variables, those only defined within a code-block. For example, variables defined within functions can only be accessed in that function.

In [69]:
def my_function(my_name):
    p = "This is {}'s function!".format(my_name)
    print(p)

a = "Dr. Hanks"
my_function(a)
print(p)

This is Dr. Hanks's function!


NameError: name 'p' is not defined

**Why did the second `print(p)` fail?**

`p` was defined within the function, which is why `print(p)` in the function did work. However, `p` is only defined within the local scope of the function `my_function`, outside the function there is no variable `p`.

## Methods

Methods are a particular type of function which is associated with a specific object (or class) and can only be called on that object: in other words methods are functions that belong to objects. Methods also have access to the data stored by the object, and in some cases can be used to modify that data, while in general Functions cannot modify the data stored by an object.

### List-like type methods

All of the built-in list-like types in Python have a few fundamental methods in common:
* `count()`: returns the number of times a specified value occurs
* `index()`: returns the index for the first element with the specified value

In [70]:
a = "Hello World!"
print(a.count('o'))
print(a.index('r'))

2
8


In [71]:
a = (0,0,1,1,2,3,3,3,4)
print(a.count(3))
print(a.index(2))

3
4


Because tuples are immutable, these are the only methods available. These methods access the data stored in the tuple, but do not attempt to modify that data. Strings are also limited, but many text-editing related methods exist for string objects, the key point is that they all *return a new string*. 

For example, the `capitalize()` method capitalizes the first letter of a string, which sounds like it changes the string, let's give it a try:

In [72]:
a = "hello World!"
print(a.capitalize())

Hello world!


In [73]:
print(a)

hello World!


### List methods
Lists are mutable, so there are many more things we can do with lists to manipulate their data in useful ways. 
* `append()`: adds single values to the end of a list
* `extend()`: adds the elements of any list-like type to the end of the current list
* `sort()`: sorts the list
* `pop()`: removes the element at the specified position

And more. In Jupyter, or iPython, you can see all of the available methods by typing the name of your list variable followed by a dot to indicate that you want to use a list method and hitting tab.

In [74]:
a = [0,1,2]
print(a)
a.append(3)
print(a)

[0, 1, 2]
[0, 1, 2, 3]


In [75]:
b = [4,5,6]
b.extend(a)
print(b)

[4, 5, 6, 0, 1, 2, 3]


In [76]:
b.sort()
print(b)

[0, 1, 2, 3, 4, 5, 6]


In [77]:
b.pop(-1)
print(b)

[0, 1, 2, 3, 4, 5]


### Numpy functions

In data analysis, a helpful feature of numpy arrays is that common mathematical operations can be performed on them and the operation will be done element-by-element without you as the programmer having to access each element directly.

In [78]:
a = np.array([1,1.5,2,2.5,3,3.5,4,4.5,5])
print(a)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [79]:
print(a * 2)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [80]:
print(a + 10)

[11.  11.5 12.  12.5 13.  13.5 14.  14.5 15. ]


In [81]:
print(a - 2)

[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]


In [82]:
print(a/5)

[0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


The Numpy library is also contains many functions that allow us to perform a variety of calculations on the array or on only one dimension (axis) of the array, allowing for rapid manipulation of large data sets.

In [83]:
print(np.mean(a))

3.0


In [84]:
print(np.max(a))

5.0


In [85]:
print(np.min(a))

1.0


In [86]:
print(np.sqrt(a))

[1.         1.22474487 1.41421356 1.58113883 1.73205081 1.87082869
 2.         2.12132034 2.23606798]


In [87]:
a2 = np.array([[0,0.5,1,1.5,2,2.5,3,3.5,4,4.5],[5,5.5,6.,6.5,7,7.5,8,8.5,9,9.5]])
print(a2)

[[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
 [5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]]


In [88]:
print(np.sqrt(a2))

[[0.         0.70710678 1.         1.22474487 1.41421356 1.58113883
  1.73205081 1.87082869 2.         2.12132034]
 [2.23606798 2.34520788 2.44948974 2.54950976 2.64575131 2.73861279
  2.82842712 2.91547595 3.         3.082207  ]]


In [89]:
print(np.max(a2))

9.5


In [90]:
print(np.max(a2,axis=0))
print(np.max(a2,axis=1))

[5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]
[4.5 9.5]


In [91]:
print(np.sum(a2))

95.0


In [92]:
print(np.sum(a2,axis=0))
print(np.sum(a2,axis=1))

[ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[22.5 72.5]


# Repeated actions and conditions

## "For" loops

A *For loop* allows you to execute a command once for each value in a collection.
* Doing calculations on the values in a list one by one requires writing out the calculation for as many values as there are in the list.
* A for loop tells Python to execute some statements once for each value in a list, a character string, or some other collection.
* “for each thing in this group, do these operations”

In [93]:
a = [1,2,3,4,5]
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

1
2
3
4
5


Or I can do this in one loop!

In [94]:
for number in a:
    print(number)

1
2
3
4
5


The `for` loop consists of a collection, a loop variable, and a body.   
```
for <loop variable> in <collection>:  
    body
```

In the above example
* `number` is the loop variable: this is what changes for each iteration of the loop
* `a` is the collection that the loop runs over
* `print(number)` is the body: this specifies what to do for each value in the collection

### Loop syntax

The first line of the `for` loop must end with a colon and the body must be indented. This syntax is not unique to `for` loops, but is the basic syntax for code blocks:
* The colon at the end of the first line signals the start of a block of statements.
* Python uses indentation rather than {} or begin/end to show nesting.
  * Any consistent indentation is legal, but almost everyone uses four spaces.
  * Indents are always meaningful

In [95]:
for number in a:
print(number)

IndentationError: expected an indented block (<ipython-input-95-463e2dfe2066>, line 2)

In [96]:
for number in [2, 3, 5]
    print(number)

SyntaxError: invalid syntax (<ipython-input-96-a0e1f235821e>, line 1)

In [97]:
a = [0,1,2]
    b = [3,4,5]

IndentationError: unexpected indent (<ipython-input-97-12d18f9defc7>, line 2)

### Loop syntax cont'd

* Loop variables can be called anything, they are created on demand and meaningless - except to you and others reading your code
* The body of the loop can contain many statements - the end of the loop is indicated by the first line of code that is not indented to the same level.
* The loop variable and any variables created inside the for loop have *global* scope

**NOTE:** In many languages, loops and conditionals (for, while; if, else) also act as scope blocks. This is not the case in Python. In Python, scope is set by functions, classes, and modules.

For example:

In [98]:
for number in a:
    print(number)
    number_mod = number + 5
    print(number_mod)

print("The for loop has finished at {},{}".format(number, number_mod))

1
6
2
7
3
8
4
9
5
10
The for loop has finished at 5,10


### range

You can iterate over a sequence of numbers using the `range` function, which has a few options for input arguments:
* `range(N)` will iterate from `0` to `N-1`
* `range(m,n)` will iterate from `m` to `n-1`
* `range(m,n,s)` will iterate from `m` to `n-1` with a step size of `s` (the default is 1)

In [99]:
for i in range(5):
    print(i)

0
1
2
3
4


In [100]:
for i in range(2,5):
    print(i)

2
3
4


In [101]:
for i in range(1,10,3):
    print(i)

1
4
7


## Conditionals: if/else

If we want to take a different action depending on some condition, we can do this with an `if` statement. We give the `if` statement a condition which will return a boolean (True/False) depending on whether the condition is passed or not. If the condition returns `True` the code block within the `if` statement will be exectued, if it returns `False`, the code block will be skipped.

In [102]:
numbers = [1,2,3,4,5]
for a in range(5):
    if a > 2:
        print(a)

3
4


`else` allows you to apply some condition such that one code block will be executed if the condition is passed and another block of code will be executed. Only one or the other block will ever execute.

In [103]:
numbers = [1,2,3,4,5]
for a in range(5):
    if a < 3:
        print('less')
    else:
        print('greater')
print('done')

less
less
less
greater
greater
done


Finally, we can chain multiple conditions together with `elif`:

In [104]:
for a in range(5):
    if a < 3:
        print('less')
    elif a == 3:
        print('equal')
    else:
        print('greater')
print('done')

less
less
less
equal
greater
done


**NOTE:** when testing if two values are equal we use `==` rather than `=`, which is used to assign values to variables. 

We can also use `and` and `or` to to combine conditions. These work like logical and and or statements, a statement with `and` will hold true only if both conditons are true and a statement with `or` will be true if either statement is true. 

In [105]:
numbers = [0,1,2,3,4,5]
for a in range(5):
    if (a >= 1) and (a <= 3):
        print("{} is in the range 1 to 3".format(a))
    else:
        print("{} is either less than 1 or greater than 3".format(a))

0 is either less than 1 or greater than 3
1 is in the range 1 to 3
2 is in the range 1 to 3
3 is in the range 1 to 3
4 is either less than 1 or greater than 3


In [106]:
for a in range(5):
    if (a < 1) or (a > 3):
        print("{} is outside the range 1 to 3".format(a))
    else:
        print("{} is in the range 1 to 3".format(a))

0 is outside the range 1 to 3
1 is in the range 1 to 3
2 is in the range 1 to 3
3 is in the range 1 to 3
4 is outside the range 1 to 3


### Notes on syntax

* We have been throwing around some comparison opperators which I will summarize here: 
  * `<` - less than
  * `>` - greater than
  * `<=` - less than or equal to
  * `>=` - greater than or equal to
  * `==` - equal to
* When using multiple conditions with `and` or `or`, you should isolate each condition with parentheses.

## "While" loops

Like for loops, *while loops* allow you to execute the same command many times. In this case, the continued exectution of the command is dependent on a *condition*.

In [107]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


**Can you think of any dangers with using `while` loops?**  
**Hint:** what would happen if you made your while loop with `while True:`?

**Why might you want to use a `while` loop rather than a `for` loop?**

### break

You can exit a `while` loop early with the `break` command. This is how we can save ourselves from inifite `while` loops!  
**NOTE:** You can also use `break` in `for` loops, it will do the same thing - exit the loop.

In [108]:
count = 0
while count < 10:
    print(count)
    if count > 5:
        break
    count += 1

0
1
2
3
4
5
6


### continue
You can skip the current block of code and return the start of the `for` or `while` loop with `continue`:

In [109]:
for a in range(10):
    if a % 2 == 0:
        continue
    print(a)

1
3
5
7
9


### else with for and while

You can add an `else` statement following your `for` or `while` loop which will execute if the `for` or `while` condition is not met just like it does with `if` statements.  

**What is the condition for a `for` loop?**

`for` loops move through elements of a collection using iteration, creating an iterator that steps through the collection until the end of the collection is reached. The implicit condition being evaluated in that process is that the end of the collection has not been reached. The `for` loop terminates when that condition is no-longer met, i.e. when the end of the collection is reached.

The `else` statement will not be exectued if you `break` out of the loop early, because the loop condition was always met, you simply left the loop. This can be especially useful in debugging, evaluating idosyncratic code behavior, or if you want to do something different when the loop reaches the end normally rather than ending early under your `break` condition.

## For loops revisited

We've looked at examples of `for` loops using basic numerical lists and the `range` function. But I told you that we can use any type of collection, so we'll now try a few more examples.

In [110]:
names = ["Rob","Bob","Bill","Will"]
for name in names:
    print(name)

Rob
Bob
Bill
Will


In [111]:
my_collection = ["Hello",5,7.5,["Good","bye"]]
for element in my_collection:
    print(element)

Hello
5
7.5
['Good', 'bye']


**What if we wanted to also keep track of the index of the current element as we loop through them?**

Well, we could create a counter:

In [112]:
names = ["Rob","Bob","Bill","Will"]
i = 0
for name in names:
    print("{} is number {}".format(name,i+1))
    i += 1

Rob is number 1
Bob is number 2
Bill is number 3
Will is number 4


Python as a built in function that can save us some work (and run time) called `enumerate`:

In [113]:
names = ["Rob","Bob","Bill","Will"]
for i,name in enumerate(names):
    print("{} is number {}".format(name,i+1))

Rob is number 1
Bob is number 2
Bill is number 3
Will is number 4


**How is this working?**

`enumerate` is a function that takes the collection you want to iterate over as an argument. It returns an enumerate object which can then be iterated over, returning a tuple of the index and value at that iteration. You can also make a list of those tuples.

In [114]:
names = ["Rob","Bob","Bill","Will"]
list(enumerate(names))

[(0, 'Rob'), (1, 'Bob'), (2, 'Bill'), (3, 'Will')]

In [115]:
for el in enumerate(names):
    print(el)

(0, 'Rob')
(1, 'Bob')
(2, 'Bill')
(3, 'Will')


Finally, there is an additional optional argument: the starting value for the index counter - this does not change where in the list you start, it just sets an offset for the index value.

In [116]:
names = ["Rob","Bob","Bill","Will"]
for i,name in enumerate(names,10):
    print("{} is number {}".format(name,i))

Rob is number 10
Bob is number 11
Bill is number 12
Will is number 13


## List comprehension

